apiVersion: v2
name: app-helm
description: A Helm chart for Kubernetes

type: application

version: 0.3.0

appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 10.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database