replicaCount: 1

environment:
  NODE_PATH: development

app:
  nameOverride: myapplication
  image:
    repository: tyku/homework_5
    imagePullPolicy: Always
    tag: latest
  containerPort: 8000
  service:
    type: ClusterIP
    port: 80


migration:
  repository: tyku/homework_5
  imagePullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/artem($|/)(.*)
          pathType: Prefix
  tls: []

identity:
  tokenKey: "123sadsjk3h"

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"

