replicaCount: 1

environment:
  NODE_PATH: development

applicationPort: 8000

migration:
  repository: tyku/hw_stream_processing
  imagePullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/artem($|/)(.*)
          pathType: Prefix
  tls: []

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"

kafka:
  enabled: true
  port: "9092"
  broker: kafka-0.kafka-headless.default.svc.cluster.local:9092
