---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceInstance.nameOverride }}
  namespace: default
spec:
  type: {{ .Values.serviceInstance.service.type }}
  selector:
    app: {{ .Values.serviceInstance.nameOverride }}
  ports:
    - port: 80
      name: http
      targetPort: http
