---
apiVersion: v1
kind: Service
metadata:
  name: homework-5
  namespace: default
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: homework-5
  ports:
    - port: 80
      name: http
      targetPort: http
