---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  type: {{ .Values.serviceInstance.service.type }}
  selector:
    app: user-service
  ports:
    - port: 80
      name: http
      targetPort: http
